# 🧠😂🔥 Prometheus конфігурація для україномовного бота 🧠😂🔥

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager конфігурація
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Правила алертів
rule_files:
  - "alert_rules.yml"

# Налаштування збору метрик
scrape_configs:
  # Сам Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Україномовний Telegram бот
  - job_name: 'ukrainian-telegram-bot'
    static_configs:
      - targets: ['bot:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    
    # Додаткові лейбли
    static_configs:
      - targets: ['bot:8080']
        labels:
          service: 'telegram-bot'
          environment: 'production'
          language: 'ukrainian'

  # PostgreSQL метрики (якщо використовується postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis метрики (якщо використовується redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node Exporter (системні метрики)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # cAdvisor (Docker контейнери)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Nginx метрики (якщо налаштовано)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

# ===== ДОДАТКОВІ НАЛАШТУВАННЯ =====

# Retention policy
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB

# Remote write (для довгострокового зберігання)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     basic_auth:
#       username: "user"
#       password: "password"

# Remote read
# remote_read:
#   - url: "https://your-remote-storage/api/v1/read"
#     basic_auth:
#       username: "user"
#       password: "password"

---
# alert_rules.yml - Правила алертів

groups:
  - name: telegram-bot-alerts
    rules:
      # Бот недоступний
      - alert: BotDown
        expr: up{job="ukrainian-telegram-bot"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Україномовний Telegram бот недоступний"
          description: "Бот не відповідає протягом {{ $value }} хвилин"

      # Високе використання CPU
      - alert: HighCPUUsage
        expr: rate(process_cpu_seconds_total{job="ukrainian-telegram-bot"}[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Високе використання CPU"
          description: "CPU використання {{ $value }}% протягом 5 хвилин"

      # Високе використання пам'яті
      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes{job="ukrainian-telegram-bot"} / 1024 / 1024 > 512
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Високе використання пам'яті"
          description: "Використання пам'яті {{ $value }}MB протягом 5 хвилин"

      # Багато помилок
      - alert: HighErrorRate
        expr: rate(telegram_bot_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Висока частота помилок"
          description: "{{ $value }} помилок за секунду протягом 2 хвилин"

      # База даних недоступна
      - alert: DatabaseDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "База даних недоступна"
          description: "PostgreSQL не відповідає протягом {{ $value }} хвилин"

      # Redis недоступний
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Redis недоступний"
          description: "Redis не відповідає протягом {{ $value }} хвилин"

      # Мало активних користувачів
      - alert: LowActiveUsers
        expr: telegram_bot_active_users < 10
        for: 30m
        labels:
          severity: info
        annotations:
          summary: "Мало активних користувачів"
          description: "Тільки {{ $value }} активних користувачів протягом 30 хвилин"

      # Довга черга модерації
      - alert: LongModerationQueue
        expr: telegram_bot_pending_content > 50
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Довга черга модерації"
          description: "{{ $value }} елементів контенту очікують модерації"

      # Багато неуспішних запитів до AI API
      - alert: HighAIAPIFailures
        expr: rate(openai_api_failures_total[5m]) > 0.1
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Багато неуспішних запитів до OpenAI API"
          description: "{{ $value }} неуспішних запитів за секунду"

  - name: system-alerts
    rules:
      # Мало вільного місця на диску
      - alert: LowDiskSpace
        expr: (node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Мало вільного місця на диску"
          description: "Тільки {{ $value }}% вільного місця залишилось"

      # Високе навантаження системи
      - alert: HighSystemLoad
        expr: node_load1 > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Високе навантаження системи"
          description: "Load average: {{ $value }} протягом 5 хвилин"